### ISSUE TITLE
Castform dynamic image asset error with no encounter

### ISSUE THREAD

**Issue by darkcity82** [SenorKarlos/RocketMap#77]
During an initial scan without  encounter I noticed that there was an error creating the automatic casform image. Here is the error:

[2018-03-09 20:40:06,766] ERROR in app: Exception on /pkm_img [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/Biel/IV/RocketMap/pogom/app.py", line 124, in pokemon_img
    shiny=shiny)
  File "/root/Biel/IV/RocketMap/pogom/dyn_img.py", line 74, in get_pokemon_raw_icon
    source, target = pokemon_asset_path(pkm, classifier='icon', gender=gender, form=form, costume=costume, weather=weather, shiny=shiny)
  File "/root/Biel/IV/RocketMap/pogom/dyn_img.py", line 259, in pokemon_asset_path
    gendersuffix = '{}'.format(Gender.Name(gender))
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/enum_type_wrapper.py", line 56, in Name
    self._enum_type.name, number))
TypeError: %d format: a number is required, not NoneType

As soon as I put the encounter I did not have the error after the old spawn not encounter disappeared and the image of castform is show on the map

**Comment by rlodev67** [comment]
bug introducted with #61 
A check for gender var need to be added at dyn_img line 259
